version: '3.1'

services:
  springboot:
    image: shareefmj/spring-boot-mongo:VERSION
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=shareef
    - MONGO_DB_PASSWORD=shareef@123
    ports:
      - 9090:8080
    depends_on:
      - mongo
    networks:
    - springappnetwork  
    docker stack deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=shareef
    - MONGO_INITDB_ROOT_PASSWORD=shareef@123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
   
    
networks:
  springappnetwork:
  
